export const UPDATE_SERVICE = 'UPDATE_SERVICE';
export const UPDATE_TIMER_FIND_JOB = 'UPDATE_TIMER_FIND_JOB';
export const CHANGE_NEW_JOB = 'CHANGE_NEW_JOB';
export const CHANGE_JOB_WITHOUT_ANSWER = 'CHANGE_JOB_WITHOUT_ANSWER';
export const CLEAN_JOB_WITHOUT_ANSWER = 'CLEAN_JOB_WITHOUT_ANSWER';